// GENERATED by relay/build.mjs from relay.template.js + blocks lifted from portal/src/index.js. Do not edit by hand.
// Mazel relay: a public cache for the Fly stage. Runs on the company account.
//
// It is a cache: deleting it loses nothing any portal doesn't hold.
//
// It never carries a message between two people (spec §7.5, the cache principle). It caches signed public
// casts and cards, answers searches over them, keeps the name@mazel directory from signed records
// portals publish, and tells a subscribed portal that a matching cast exists. Every intro, reply and
// connect still goes portal to portal on the A2A wire.
//
// No accounts. A signature is the only auth. TTL on every record.
//
// POST /cast            signed public need-cast or card-cast          (7-day TTL)
// GET  /search?q=&tags= the portal's paraphrase scorer over cached casts
// POST /subscribe       A2A push config signed by the subscriber; on a matching new cast the relay
//                       POSTs a signed find.hit to the subscriber's door         (30-day TTL)
// POST /publish         signed handle record or rotation record -> the directory  (90-day TTL)
// GET  /.well-known/mazel/<name>.json   the directory record for name@mazel
// GET  /.well-known/relay.json          this relay's public key
// GET  /                the sentence above

const RELAY_VERSION = "0.5.2";   // stamped by relay/build.mjs from the portal
const HAAH_URI = "https://mazel.ai/ext/haah/v1";
const CAST_TTL = 60 * 60 * 24 * 7;
const SUB_TTL = 60 * 60 * 24 * 30;
const DIR_TTL = 60 * 60 * 24 * 90;
const MAX_RESULTS = 10;
const SENTENCE = "It is a cache: deleting it loses nothing any portal doesn't hold.";

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const fwd = (request.headers.get("x-forwarded-proto") || "").split(",")[0].trim();
    const origin = fwd === "https" || fwd === "http" ? `${fwd}://${url.host}` : url.origin;
    const p = url.pathname;
    try {
      if (p === "/" && request.method === "GET") {
        return text(`Mazel relay ${RELAY_VERSION}. ${SENTENCE}\nCasts: POST /cast   Search: GET /search?q=   Subscribe: POST /subscribe   Directory: GET /.well-known/mazel/<name>.json\n`);
      }
      if (p === "/.well-known/relay.json" && request.method === "GET") {
        const s = await getSigning(env);
        return json({ relay: origin, version: RELAY_VERSION, publicKey: s.pub, keyId: s.kid, sentence: SENTENCE });
      }
      const rec = p.match(/^\/\.well-known\/mazel\/([a-z0-9][a-z0-9._-]*)\.json$/);
      if (rec && request.method === "GET") return await directoryGet(env, rec[1].toLowerCase());
      if (p === "/publish" && request.method === "POST") return await publish(env, await bounded(request));
      if (p === "/cast" && request.method === "POST") return await cast(env, origin, await bounded(request));
      if (p === "/search" && request.method === "GET") return await search(env, url);
      if (p === "/subscribe" && request.method === "POST") return await subscribe(env, await bounded(request));
      if (p === "/unsubscribe" && request.method === "POST") return await unsubscribe(env, await bounded(request));
      return json({ error: "not found" }, 404);
    } catch (e) {
      return json({ error: e.message || String(e) }, 400);
    }
  },
};

// ---------------------------------------------------------------------------
// Storage helpers
// KV list() returns at most 1000 keys and a cursor. Reading one page and stopping meant that once
// the cache held more than a thousand casts, search silently only ever saw the first thousand.
const MAX_SCAN = 5000;
async function kvList(env, prefix, cap = MAX_SCAN) {
  const out = [];
  let cursor;
  do {
    const list = await env.RELAY.list(cursor ? { prefix, cursor } : { prefix });
    for (const k of list.keys) {
      const v = await env.RELAY.get(k.name);
      if (v) out.push({ key: k.name, ...JSON.parse(v) });
      if (out.length >= cap) return out;
    }
    cursor = list.list_complete === false ? list.cursor : null;
  } while (cursor);
  return out;
}

// Ceilings for anything an anonymous caller can put in the cache. Without them one request stores
// as much as it likes, and every later search pays to read it.
const MAX_CAST_BYTES = 16 * 1024;
// Every body this cache accepts has a ceiling before it is even parsed.
async function bounded(request) {
  if (Number(request.headers.get("content-length") || 0) > MAX_CAST_BYTES) throw new Error(`body over ${MAX_CAST_BYTES} bytes`);
  const raw = await request.text();
  if (raw.length > MAX_CAST_BYTES) throw new Error(`body over ${MAX_CAST_BYTES} bytes`);
  return JSON.parse(raw);
}
const CAST_FRESH_MS = 1000 * 60 * 60 * 24 * 2;
const fresh = (at) => {
  const t = Date.parse(at || "");
  if (!Number.isFinite(t)) return false;
  const age = Date.now() - t;
  return age > -60000 && age < CAST_FRESH_MS;
};
const MAX_TAGS_IN = 12;
const MAX_GLOSSES = 12;
const MAX_GLOSS_LEN = 200;
const MAX_SUBS_PER_KEY = 3;
const MAX_FANOUT = 50;
// Per key, per day. MAX_FANOUT bounded one cast; nothing bounded how many casts, so one anonymous
// key could keep the relay posting into every subscriber's mailbox all day at the operator's cost.
const MAX_CASTS_PER_KEY_PER_DAY = 100;
async function underCap(env, what, cap) {
  const key = `cap:${what}:${new Date().toISOString().slice(0, 10)}`;
  const n = Number((await env.RELAY.get(key)) || 0);
  if (n >= cap) return false;
  await env.RELAY.put(key, String(n + 1), { expirationTtl: 60 * 60 * 36 });
  return true;
}
const capTags = (v) => (Array.isArray(v) ? v : []).map(normalizeTag).filter(Boolean).slice(0, MAX_TAGS_IN);
const capGlosses = (g) => {
  const out = {};
  if (!g || typeof g !== "object") return out;
  for (const k of Object.keys(g).slice(0, MAX_GLOSSES)) {
    const tag = normalizeTag(k);
    if (tag) out[tag] = String(g[k] == null ? "" : g[k]).slice(0, MAX_GLOSS_LEN);
  }
  return out;
};

// A name in this directory is ASCII, and the separators people use to make a lookalike are folded
// away: lea, l.e.a and le-a are one name, and anything outside a-z0-9 is refused outright rather
// than left to render as a homoglyph in a line of chat.
function dirName(local) {
  const folded = String(local || "").toLowerCase().normalize("NFKC").replace(/[._-]/g, "");
  if (!/^[a-z0-9]{1,32}$/.test(folded)) return null;
  return folded;
}
const put = (env, key, obj, ttl) => env.RELAY.put(key, JSON.stringify(obj), { expirationTtl: ttl });

async function stableId(...parts) {
  const data = new TextEncoder().encode(parts.join("|"));
  const hash = await crypto.subtle.digest("SHA-256", data);
  return [...new Uint8Array(hash)].map((b) => b.toString(16).padStart(2, "0")).join("").slice(0, 32);
}

// ---------------------------------------------------------------------------
// The relay's own key: signs the find.hit it delivers to subscribers, so a portal can tell a hit
// really came from the relay it subscribed to.
async function getSigning(env) {
  const raw = await env.RELAY.get("config:signing");
  if (raw) return JSON.parse(raw);
  const pair = await crypto.subtle.generateKey({ name: "Ed25519" }, true, ["sign", "verify"]);
  const priv = await crypto.subtle.exportKey("jwk", pair.privateKey);
  const pub = b64u(await crypto.subtle.exportKey("raw", pair.publicKey));
  const rec = { priv, pub, kid: await keyId(pub), createdAt: new Date().toISOString() };
  await env.RELAY.put("config:signing", JSON.stringify(rec));
  return rec;
}
async function relaySign(env, payload) {
  const s = await getSigning(env);
  const key = await crypto.subtle.importKey("jwk", s.priv, { name: "Ed25519" }, false, ["sign"]);
  const sig = await crypto.subtle.sign({ name: "Ed25519" }, key, new TextEncoder().encode(canonical(payload)));
  return { ...payload, sig: b64u(sig), kid: s.kid };
}

// ---------------------------------------------------------------------------
// Directory: name@mazel resolves here. A record is accepted when it is signed by the key it names,
// and, for a name already on file, when a valid rotation chain leads from the stored key to the new one.
async function directoryGet(env, name) {
  const folded = dirName(name);
  if (!folded) return json({ error: "no such handle in this directory", name }, 404);
  const raw = await env.RELAY.get(`dir:${folded}`);
  if (!raw) return json({ error: "no such handle in this directory", name }, 404);
  const { storedAt, ...record } = JSON.parse(raw);
  return json(record);
}

async function chainLinks(fromKey, toKey, rotations) {
  let cur = fromKey;
  if (cur === toKey) return true;
  for (const r of rotations || []) {
    if (r.oldKey !== cur) continue;
    const { sig, kid, newSig, ...base } = r;
    const okOld = await verifyPayload({ ...base, sig }, r.oldKey);
    const okNew = await verifyPayload({ ...base, sig: newSig }, r.newKey);
    if (!okOld || !okNew) return false;
    cur = r.newKey;
    if (cur === toKey) return true;
  }
  return false;
}

// Ask the portal the record points at whether it agrees. It must serve the same name under the
// same key: that is what makes squatting cost a portal rather than a single HTTP request.
async function servesItself(record, name) {
  const base = String(record.rpc || record.cardUrl || "").replace(/\/(a2a|card|\.well-known\/.*)$/, "");
  if (!/^https:\/\//.test(base)) return false;
  try {
    const res = await fetch(`${base}/.well-known/mazel/${name}.json`, { headers: { accept: "application/json" } });
    if (!res.ok) return false;
    const served = await res.json();
    return served && served.publicKey === record.publicKey && (await verifyPayload(served, served.publicKey));
  } catch {
    return false;
  }
}

async function publish(env, record) {
  if (!record || typeof record !== "object") throw new Error("body must be a signed handle record");
  const handle = String(record.handle || "").toLowerCase();
  const m = handle.match(/^([a-z0-9][a-z0-9._-]*)@(mazel|mazel\.ai)$/);
  if (!m) throw new Error("this directory holds name@mazel (name@mazel.ai) only");
  if (!record.publicKey || !record.cardUrl || !record.sig) throw new Error("record needs publicKey, cardUrl, sig");
  if (!(await verifyPayload(record, record.publicKey))) throw new Error("record is not signed by the key it names");
  const name = dirName(m[1]);
  if (!name) throw new Error("a name in this directory is 1-32 characters of a-z and 0-9; dots, dashes and underscores fold away and anything else is refused");
  // The name has to be backed by a portal that serves the same record under the same key. A
  // directory that takes anyone's word for it hands out names to whoever asks first, for free.
  if (!(await servesItself(record, name))) {
    throw new Error(`the portal at ${record.rpc || record.cardUrl} does not serve this same record at /.well-known/mazel/${name}.json, so this name is not yours to publish`);
  }
  const existingRaw = await env.RELAY.get(`dir:${name}`);
  if (existingRaw) {
    const existing = JSON.parse(existingRaw);
    if (existing.publicKey !== record.publicKey) {
      const ok = await chainLinks(existing.publicKey, record.publicKey, record.rotations);
      if (!ok) throw new Error("name is held by another key and no valid rotation chain leads to this one");
    }
    if (existing.timestamp && record.timestamp && record.timestamp < existing.timestamp) throw new Error("record is older than the one on file");
  }
  // Stored verbatim: handle is inside the signed bytes, so the record is never rewritten (only storedAt rides alongside and is stripped on read).
  await put(env, `dir:${name}`, { ...record, storedAt: new Date().toISOString() }, DIR_TTL);
  return json({ ok: true, handle: `${name}@mazel.ai`, keyId: await keyId(record.publicKey), rotations: (record.rotations || []).length });
}

// ---------------------------------------------------------------------------
// Casts: a signed public need or card. The signer's public key rides in the cast; a cast whose
// signature does not verify is dropped. Only public-tier material is ever accepted here.
async function cast(env, origin, body) {
  if (!body || typeof body !== "object") throw new Error("body must be a signed cast");
  if (!body.publicKey || !body.sig) throw new Error("cast needs publicKey and sig");
  if (!(await verifyPayload(body, body.publicKey))) throw new Error("cast is not signed by its publicKey");
  const blind = body.kind === "blind";
  if (!blind && body.visibility && body.visibility !== "public") throw new Error("only public casts belong here");
  if (blind && (!Array.isArray(body.fp) || !body.fp.length)) throw new Error("a blind cast carries a fingerprint and nothing else");
  const kind = blind ? "blind" : body.kind === "card" ? "card" : "need";
  const handle = String(body.handle || "").toLowerCase();
  if (!handle.includes("@")) throw new Error("cast needs a handle");
  // If this directory holds the name, only the key that holds it may cast under it.
  const local = dirName((handle.match(/^([^@]+)@(mazel|mazel\.ai)$/) || [])[1] || "");
  if (local) {
    const heldRaw = await env.RELAY.get(`dir:${local}`);
    if (heldRaw && JSON.parse(heldRaw).publicKey !== body.publicKey) {
      throw new Error(`${handle} is held in this directory by another key; casts under that name must be signed by it`);
    }
  }
  if (!fresh(body.castAt)) throw new Error("cast is missing a recent castAt; a cast with no time in its signature can be replayed forever");
  if (!(await underCap(env, `cast:${body.publicKey.slice(0, 16)}`, MAX_CASTS_PER_KEY_PER_DAY))) throw new Error("that key has cast enough for one day here");
  // Keyed by the signing key, not by the handle. Keying by handle let anyone with a fresh keypair
  // overwrite the cached card of a handle they do not own, and every portal that searched picked up
  // their rpc for that person.
  const id = kind === "card"
    ? await stableId("card", body.publicKey)
    : await stableId(kind, body.publicKey, body.needId || body.needText || "");
  // A blind cast is stored with no text of any kind: buckets, an id, and who to answer.
  const record = blind ? {
    id, kind, handle, publicKey: body.publicKey, rpc: body.rpc || null, needId: body.needId || null,
    fp: body.fp.slice(0, 64).map(String), tier: "world", castAt: body.castAt,
  } : {
    id, kind, handle, publicKey: body.publicKey, cardUrl: body.cardUrl || null, rpc: body.rpc || null,
    needId: body.needId || null, needText: String(body.needText || "").slice(0, 300), needTags: (body.needTags || []).map(normalizeTag).filter(Boolean),
    have: capTags(body.have), glosses: capGlosses(body.glosses),
    description: String(body.description || "").slice(0, 600), tier: "world", castAt: new Date().toISOString(),
  };
  record.castAt = body.castAt;   // the signed time, not the time it happened to arrive
  // A blind cast is a confirmation oracle for whoever holds it, so it is held for a day rather
  // than a week: long enough to be matched, short enough not to be a standing question.
  await put(env, `cast:${kind}:${id}`, record, kind === "blind" ? 60 * 60 * 24 : CAST_TTL);
  const notified = await notifySubscribers(env, origin, record);
  return json({ ok: true, id, kind, expiresInSeconds: CAST_TTL, notified, sentence: SENTENCE });
}

// A cast looks like a known card to the scorer: needs match against haves, and a need-cast is also
// searchable by its own text so two people looking for each other can meet.
function castAsCard(c) {
  return { url: c.cardUrl, handle: c.handle, rpc: c.rpc, description: c.description || c.needText || "", have: c.kind === "card" ? c.have : [], glosses: c.glosses || {}, tier: "world", need: c.needTags || [] };
}

async function search(env, url) {
  const q = String(url.searchParams.get("q") || "").trim();
  const tags = [...new Set(String(url.searchParams.get("tags") || "").split(",").map(normalizeTag).filter(Boolean))];
  if (!q && !tags.length) throw new Error("q or tags required");
  const needWords = needWordsFor(q, tags);
  const casts = await kvList(env, "cast:");
  const scored = [];
  for (const c of casts) {
    const card = castAsCard(c);
    // card-casts match on their haves; need-casts match on the words of the need itself
    const m = c.kind === "card" ? scoreCard(card, tags, needWords) : scoreNeedCast(c, tags, needWords);
    if (m.score >= 2 && m.matched.length) scored.push({ c, m, card });
  }
  scored.sort((a, b) => b.m.score - a.m.score || a.c.handle.localeCompare(b.c.handle));
  const results = scored.slice(0, MAX_RESULTS).map(({ c, m, card }) => ({
    kind: c.kind, handle: c.handle, cardUrl: c.cardUrl, rpc: c.rpc, publicKey: c.publicKey, tier: "world",
    matched: m.matched, score: m.score, why: c.kind === "card" ? whyLine(card, m, q || tags.join(" ")) : `${c.handle} is looking for the same thing: "${c.needText}".`,
    needText: c.needText || null, have: card.have, glosses: card.glosses, castAt: c.castAt,
  }));
  return json({ query: q, tags, searched: casts.length, results, sentence: SENTENCE });
}

function scoreNeedCast(c, tags, needWords) {
  const theirs = new Set([...(c.needTags || []).flatMap(words), ...words(c.needText)]);
  const matched = [];
  let score = 0;
  for (const t of tags) if ((c.needTags || []).includes(t)) { score += 3; matched.push(t); }
  let overlap = 0;
  for (const w of needWords) if (theirs.has(w)) overlap++;
  if (overlap >= 2) { score += overlap; if (!matched.length) matched.push(c.needTags[0] || "need"); }
  return { score, matched, descHits: 0 };
}

// ---------------------------------------------------------------------------
// Subscriptions: an A2A push-notification config signed by the subscribing portal. When a new cast
// matches the subscriber's haves, the relay POSTs a signed find.hit to the subscriber's door.
async function subscribe(env, body) {
  if (!body || !body.publicKey || !body.sig) throw new Error("subscription needs publicKey and sig");
  if (!(await verifyPayload(body, body.publicKey))) throw new Error("subscription is not signed by its publicKey");
  const cfg = body.config || {};
  if (!/^https:\/\//.test(String(cfg.url || ""))) throw new Error("config.url must be https");
  const handle = String(body.handle || "").toLowerCase();
  // The url must be a portal that serves this key's own record. Without that check anyone could
  // point the relay at a third party and then trigger the fan-out with one anonymous cast.
  const local = dirName((handle.match(/^([^@]+)@(mazel|mazel\.ai)$/) || [])[1] || "");
  const host = (u) => { try { return new URL(u).host; } catch { return null; } };
  const heldRaw = local ? await env.RELAY.get(`dir:${local}`) : null;
  const held = heldRaw ? JSON.parse(heldRaw) : null;
  if (!held || held.publicKey !== body.publicKey || host(held.rpc || held.cardUrl) !== host(cfg.url)) {
    throw new Error("publish your handle record to this directory first; a subscription only goes to the portal that holds the name");
  }
  const mine = (await kvList(env, "sub:")).filter((x) => x.publicKey === body.publicKey);
  if (mine.length >= MAX_SUBS_PER_KEY) throw new Error(`a key may hold ${MAX_SUBS_PER_KEY} subscriptions here`);
  const id = await stableId("sub", handle, cfg.url);
  // No push token is kept: an unauthenticated cache is the wrong place to hold somebody's bearer.
  const record = { id, handle, publicKey: body.publicKey, url: cfg.url, taskId: String(cfg.taskId || "*"), have: capTags(body.have), glosses: capGlosses(body.glosses), haveFp: (Array.isArray(body.haveFp) ? body.haveFp : []).slice(0, 64).map(String), description: String(body.description || "").slice(0, 600), createdAt: new Date().toISOString() };
  await put(env, `sub:${id}`, record, SUB_TTL);
  return json({ ok: true, id, expiresInSeconds: SUB_TTL, sentence: SENTENCE });
}

async function unsubscribe(env, body) {
  if (!body || !body.publicKey || !body.sig) throw new Error("needs publicKey and sig");
  if (!(await verifyPayload(body, body.publicKey))) throw new Error("not signed by its publicKey");
  const id = await stableId("sub", String(body.handle || "").toLowerCase(), String((body.config || {}).url || ""));
  await env.RELAY.delete(`sub:${id}`);
  return json({ ok: true, id });
}

// A blind cast is matched on buckets alone. The answer says a number and nothing else: no text
// travels in either direction until the person who owns the need decides it should.
async function notifyBlind(env, origin, castRecord) {
  const subs = await kvList(env, "sub:");
  let delivered = 0;
  for (const s of subs) {
    if (delivered >= MAX_FANOUT) break;
    if (s.publicKey === castRecord.publicKey) continue;
    const overlap = fpOverlap(castRecord.fp, s.haveFp || []);
    if (overlap < FP_MATCH_MIN) continue;
    const hit = await relaySign(env, { v: 1, type: "find.hit", via: "relay", relay: origin, blind: true, castAt: new Date().toISOString(), needId: castRecord.needId, overlap, at: new Date().toISOString(), from: { handle: s.handle, cardUrl: s.url, rpc: s.url, publicKey: s.publicKey } });
    const why = `A portal may fit something you are holding back: ${overlap} signals in common. Nothing was said about what you are looking for.`;
    try {
      const res = await fetch(castRecord.rpc, {
        method: "POST", headers: { "content-type": "application/json", "A2A-Version": "1.0" },
        body: JSON.stringify({ jsonrpc: "2.0", id: hit.needId || crypto.randomUUID(), method: "SendMessage", params: { message: {
          messageId: await stableId("blind", s.id, castRecord.id), contextId: "", taskId: "*", role: "ROLE_AGENT", parts: [{ text: why }],
          metadata: { handle: `relay@${new URL(origin).host}`, cardUrl: `${origin}/.well-known/relay.json`, action: hit }, extensions: [HAAH_URI], referenceTaskIds: [] } } }),
      });
      if (res.ok) delivered++;
    } catch {}
  }
  return delivered;
}

// For a new need-cast, find subscribers whose haves fit it and deliver a find.hit to each.
async function notifySubscribers(env, origin, castRecord) {
  if (castRecord.kind === "blind") return notifyBlind(env, origin, castRecord);
  if (castRecord.kind !== "need") return 0;
  const subs = await kvList(env, "sub:");
  const needWords = needWordsFor(castRecord.needText, castRecord.needTags);
  let delivered = 0;
  for (const s of subs) {
    // A ceiling on what one anonymous cast can make this relay send. The operator pays for each.
    if (delivered >= MAX_FANOUT) break;
    if (s.handle === castRecord.handle) continue;
    const asCard = { url: s.url, handle: s.handle, rpc: s.url, description: s.description, have: s.have, glosses: s.glosses, tier: "world" };
    const m = scoreCard(asCard, castRecord.needTags, needWords);
    if (m.score < 2 || !m.matched.length) continue;
    const hit = await relaySign(env, {
      v: 1, type: "find.hit", via: "relay", relay: origin, castAt: new Date().toISOString(), needId: castRecord.needId, needText: castRecord.needText, needTags: castRecord.needTags,
      from: { handle: castRecord.handle, cardUrl: castRecord.cardUrl, rpc: castRecord.rpc, publicKey: castRecord.publicKey },
      matchedTags: m.matched, why: `${castRecord.handle} is looking for ${castRecord.needText}; you have ${m.matched.join(", ")}.`, at: new Date().toISOString(),
    });
    try {
      const res = await fetch(s.url, {
        method: "POST", headers: { "content-type": "application/json", "A2A-Version": "1.0" },
        body: JSON.stringify({ jsonrpc: "2.0", id: hit.needId || crypto.randomUUID(), method: "SendMessage", params: { message: {
          messageId: await stableId("hit", s.id, castRecord.id), contextId: "", taskId: s.taskId, role: "ROLE_AGENT", parts: [{ text: hit.why }],
          metadata: { handle: `relay@${new URL(origin).host}`, cardUrl: `${origin}/.well-known/relay.json`, action: hit }, extensions: [HAAH_URI], referenceTaskIds: [] } } }),
      });
      if (res.ok) delivered++;
    } catch {}
  }
  return delivered;
}

// ---------------------------------------------------------------------------
function json(obj, status = 200) {
  return new Response(JSON.stringify(obj, null, 2), { status, headers: { "content-type": "application/json", "access-control-allow-origin": "*" } });
}
function text(s, status = 200) {
  return new Response(s, { status, headers: { "content-type": "text/plain; charset=utf-8" } });
}

// ---- SHARED FP BEGIN (pure; lifted verbatim into the relay at build) ----
// A fingerprint for a need the person does not want to say out loud. Each word becomes a short
// prefix of its hash, so many words land in the same bucket and a bucket names none of them.
//
// What this protects: bulk harvesting, and a casual reader of the cache learning what someone is
// looking for. What it does NOT protect: a targeted attacker with a dictionary and patience. The
// prefix is short on purpose, so every bucket has company, but overlap across a whole set still
// narrows things for someone who cares. It is obfuscation with a known cost, not secrecy. Real
// private set intersection replaces it later; until then a matched-only need is safer than text
// and not safe from someone hunting you specifically.
const FP_PREFIX = 3;          // hex characters: 4096 buckets
const FP_MATCH_MIN = 2;       // buckets that must line up before anyone is told anything

async function fingerprint(words) {
  const out = new Set();
  for (const w of words) {
    const h = await crypto.subtle.digest("SHA-256", new TextEncoder().encode("mazel/fp/v1:" + w));
    out.add([...new Uint8Array(h)].map((b) => b.toString(16).padStart(2, "0")).join("").slice(0, FP_PREFIX));
  }
  return [...out].sort();
}

const fpOverlap = (a, b) => {
  const set = new Set(a || []);
  return (b || []).filter((x) => set.has(x)).length;
};
// ---- SHARED FP END ----
// ---- SHARED MATCH BEGIN (pure functions; lifted verbatim into the relay at build; a test asserts equality) ----
// Function words never count as a match. Two of these in common is not a fit.
const STOPWORDS = new Set(("a an the and or of in on at to for with by from is are be me my i you your who that this it as we our find need want looking someone somebody person people help " +
  "has have had having was were been being will would could should can may might must shall do does did done doing " +
  "not no nor own real more most some any all each every both few than then there here when where which what how why also just only very " +
  "into onto over under about after before again ever never now new old one two three get got give gave like make made take took come came go went " +
  "its his her their them they she he him hers ours yours out off per via yes too able much many such same other another whether while still").split(/\s+/));

function normalizeTag(t) {
  return String(t || "")
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function words(text) {
  return String(text || "").toLowerCase().replace(/[^a-z0-9\s-]/g, " ").split(/[\s-]+/).filter((w) => w.length > 2 && !STOPWORDS.has(w));
}

// Deterministic match of need tags against one known card's haves.
function scoreCard(card, needTags, needWords) {
  const matched = [];
  let score = 0;
  const haveGloss = (t) => (card.glosses && card.glosses[t]) || "";
  for (const h of card.have) {
    const hw = new Set([...words(h), ...words(haveGloss(h))]);
    if (needTags.includes(h)) {
      score += 3;
      matched.push(h);
      continue;
    }
    let overlap = 0;
    for (const t of needTags) for (const w of words(t)) if (hw.has(w)) overlap++;
    if (overlap) {
      score += 2 * overlap;
      matched.push(h);
      continue;
    }
    let gl = 0;
    for (const w of needWords) if (hw.has(w)) gl++;
    if (gl) {
      score += gl;
      matched.push(h);
    }
  }
  const dw = new Set(words(card.description));
  let desc = 0;
  for (const w of needWords) if (dw.has(w)) desc++;
  score += desc;
  return { score, matched, descHits: desc };
}

function whyLine(card, m, needText) {
  const tag = m.matched[0];
  const gloss = tag && card.glosses && card.glosses[tag] ? ` ("${card.glosses[tag]}")` : "";
  if (tag) return `You need ${needText}; ${card.handle} has ${tag}${gloss}.`;
  return `You need ${needText}; ${card.handle}'s card mentions it (${m.descHits} matching words in their description).`;
}

// Score one card against a thread's need. Shared by find and by add_known_card,
// so an open thread keeps collecting candidates as new cards arrive.
function candidateFor(card, needTags, needWords, needText) {
  const m = scoreCard(card, needTags, needWords);
  if (m.score < 2 || !m.matched.length) return null;
  return { cardUrl: card.url, handle: card.handle, rpc: card.rpc, tier: card.tier, score: m.score, matchedTags: m.matched, why: whyLine(card, m, needText), addedAt: new Date().toISOString() };
}

function needWordsFor(needText, needTags) {
  return [...new Set([...words(needText), ...needTags.flatMap(words)])];
}
// ---- SHARED MATCH END ----

// ---- SHARED SIGNING BEGIN (pure helpers; lifted verbatim into the relay at build) ----
const b64u = (buf) => btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
const unb64u = (s) => Uint8Array.from(atob(String(s).replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - (s.length % 4)) % 4)), (c) => c.charCodeAt(0));

// Canonical JSON: sorted keys, no whitespace, so both sides sign the same bytes.
function canonical(v) {
  if (v === null || typeof v !== "object") return JSON.stringify(v);
  if (Array.isArray(v)) return "[" + v.map(canonical).join(",") + "]";
  return "{" + Object.keys(v).sort().map((k) => JSON.stringify(k) + ":" + canonical(v[k])).join(",") + "}";
}

async function keyId(publicKeyB64u) {
  const h = await crypto.subtle.digest("SHA-256", unb64u(publicKeyB64u));
  return b64u(h).slice(0, 16);
}

// Verify a signed object against a base64url raw Ed25519 public key. The sig and kid fields are
// excluded from the signed bytes.
async function verifyPayload(signed, pubB64u) {
  try {
    const { sig, kid, ...payload } = signed;
    const key = await crypto.subtle.importKey("raw", unb64u(pubB64u), { name: "Ed25519" }, false, ["verify"]);
    return await crypto.subtle.verify({ name: "Ed25519" }, key, unb64u(sig), new TextEncoder().encode(canonical(payload)));
  } catch {
    return false;
  }
}
// ---- SHARED SIGNING END ----
