// GENERATED by relay/build.mjs from relay.template.js + blocks lifted from portal/src/index.js. Do not edit by hand.
// Mazel relay: a public cache for the Fly stage. Runs on the company account.
//
// It is a cache: deleting it loses nothing any portal doesn't hold.
//
// It never carries a message between two people (spec §19 row C stands). It caches signed public
// casts and cards, answers searches over them, keeps the name@mazel directory from signed records
// portals publish, and tells a subscribed portal that a matching cast exists. Every intro, reply and
// connect still goes portal to portal on the A2A wire.
//
// No accounts. A signature is the only auth. TTL on every record.
//
// POST /cast            signed public need-cast or card-cast          (7-day TTL)
// GET  /search?q=&tags= the portal's paraphrase scorer over cached casts
// POST /subscribe       A2A push config signed by the subscriber; on a matching new cast the relay
//                       POSTs a signed find.hit to the subscriber's door         (30-day TTL)
// POST /publish         signed handle record or rotation record -> the directory  (90-day TTL)
// GET  /.well-known/mazel/<name>.json   the directory record for name@mazel
// GET  /.well-known/relay.json          this relay's public key
// GET  /                the sentence above

const RELAY_VERSION = "0.4.0";
const HAAH_URI = "https://mazel.ai/ext/haah/v1";
const CAST_TTL = 60 * 60 * 24 * 7;
const SUB_TTL = 60 * 60 * 24 * 30;
const DIR_TTL = 60 * 60 * 24 * 90;
const MAX_RESULTS = 10;
const SENTENCE = "It is a cache: deleting it loses nothing any portal doesn't hold.";

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const fwd = (request.headers.get("x-forwarded-proto") || "").split(",")[0].trim();
    const origin = fwd === "https" || fwd === "http" ? `${fwd}://${url.host}` : url.origin;
    const p = url.pathname;
    try {
      if (p === "/" && request.method === "GET") {
        return text(`Mazel relay ${RELAY_VERSION}. ${SENTENCE}\nCasts: POST /cast   Search: GET /search?q=   Subscribe: POST /subscribe   Directory: GET /.well-known/mazel/<name>.json\n`);
      }
      if (p === "/.well-known/relay.json" && request.method === "GET") {
        const s = await getSigning(env);
        return json({ relay: origin, version: RELAY_VERSION, publicKey: s.pub, keyId: s.kid, sentence: SENTENCE });
      }
      const rec = p.match(/^\/\.well-known\/mazel\/([a-z0-9][a-z0-9._-]*)\.json$/);
      if (rec && request.method === "GET") return await directoryGet(env, rec[1].toLowerCase());
      if (p === "/publish" && request.method === "POST") return await publish(env, await request.json());
      if (p === "/cast" && request.method === "POST") return await cast(env, origin, await request.json());
      if (p === "/search" && request.method === "GET") return await search(env, url);
      if (p === "/subscribe" && request.method === "POST") return await subscribe(env, await request.json());
      if (p === "/unsubscribe" && request.method === "POST") return await unsubscribe(env, await request.json());
      return json({ error: "not found" }, 404);
    } catch (e) {
      return json({ error: e.message || String(e) }, 400);
    }
  },
};

// ---------------------------------------------------------------------------
// Storage helpers
async function kvList(env, prefix) {
  const list = await env.RELAY.list({ prefix });
  const out = [];
  for (const k of list.keys) {
    const v = await env.RELAY.get(k.name);
    if (v) out.push({ key: k.name, ...JSON.parse(v) });
  }
  return out;
}
const put = (env, key, obj, ttl) => env.RELAY.put(key, JSON.stringify(obj), { expirationTtl: ttl });

async function stableId(...parts) {
  const data = new TextEncoder().encode(parts.join("|"));
  const hash = await crypto.subtle.digest("SHA-256", data);
  return [...new Uint8Array(hash)].map((b) => b.toString(16).padStart(2, "0")).join("").slice(0, 32);
}

// ---------------------------------------------------------------------------
// The relay's own key: signs the find.hit it delivers to subscribers, so a portal can tell a hit
// really came from the relay it subscribed to.
async function getSigning(env) {
  const raw = await env.RELAY.get("config:signing");
  if (raw) return JSON.parse(raw);
  const pair = await crypto.subtle.generateKey({ name: "Ed25519" }, true, ["sign", "verify"]);
  const priv = await crypto.subtle.exportKey("jwk", pair.privateKey);
  const pub = b64u(await crypto.subtle.exportKey("raw", pair.publicKey));
  const rec = { priv, pub, kid: await keyId(pub), createdAt: new Date().toISOString() };
  await env.RELAY.put("config:signing", JSON.stringify(rec));
  return rec;
}
async function relaySign(env, payload) {
  const s = await getSigning(env);
  const key = await crypto.subtle.importKey("jwk", s.priv, { name: "Ed25519" }, false, ["sign"]);
  const sig = await crypto.subtle.sign({ name: "Ed25519" }, key, new TextEncoder().encode(canonical(payload)));
  return { ...payload, sig: b64u(sig), kid: s.kid };
}

// ---------------------------------------------------------------------------
// Directory: name@mazel resolves here. A record is accepted when it is signed by the key it names,
// and, for a name already on file, when a valid rotation chain leads from the stored key to the new one.
async function directoryGet(env, name) {
  const raw = await env.RELAY.get(`dir:${name}`);
  if (!raw) return json({ error: "no such handle in this directory", name }, 404);
  const { storedAt, ...record } = JSON.parse(raw);
  return json(record);
}

async function chainLinks(fromKey, toKey, rotations) {
  let cur = fromKey;
  if (cur === toKey) return true;
  for (const r of rotations || []) {
    if (r.oldKey !== cur) continue;
    const { sig, kid, newSig, ...base } = r;
    const okOld = await verifyPayload({ ...base, sig }, r.oldKey);
    const okNew = await verifyPayload({ ...base, sig: newSig }, r.newKey);
    if (!okOld || !okNew) return false;
    cur = r.newKey;
    if (cur === toKey) return true;
  }
  return false;
}

async function publish(env, record) {
  if (!record || typeof record !== "object") throw new Error("body must be a signed handle record");
  const handle = String(record.handle || "").toLowerCase();
  const m = handle.match(/^([a-z0-9][a-z0-9._-]*)@(mazel|mazel\.ai)$/);
  if (!m) throw new Error("this directory holds name@mazel (name@mazel.ai) only");
  if (!record.publicKey || !record.cardUrl || !record.sig) throw new Error("record needs publicKey, cardUrl, sig");
  if (!(await verifyPayload(record, record.publicKey))) throw new Error("record is not signed by the key it names");
  const name = m[1];
  const existingRaw = await env.RELAY.get(`dir:${name}`);
  if (existingRaw) {
    const existing = JSON.parse(existingRaw);
    if (existing.publicKey !== record.publicKey) {
      const ok = await chainLinks(existing.publicKey, record.publicKey, record.rotations);
      if (!ok) throw new Error("name is held by another key and no valid rotation chain leads to this one");
    }
    if (existing.timestamp && record.timestamp && record.timestamp < existing.timestamp) throw new Error("record is older than the one on file");
  }
  // Stored verbatim: handle is inside the signed bytes, so the record is never rewritten (only storedAt rides alongside and is stripped on read).
  await put(env, `dir:${name}`, { ...record, storedAt: new Date().toISOString() }, DIR_TTL);
  return json({ ok: true, handle: `${name}@mazel.ai`, keyId: await keyId(record.publicKey), rotations: (record.rotations || []).length });
}

// ---------------------------------------------------------------------------
// Casts: a signed public need or card. The signer's public key rides in the cast; a cast whose
// signature does not verify is dropped. Only public-tier material is ever accepted here.
async function cast(env, origin, body) {
  if (!body || typeof body !== "object") throw new Error("body must be a signed cast");
  if (!body.publicKey || !body.sig) throw new Error("cast needs publicKey and sig");
  if (!(await verifyPayload(body, body.publicKey))) throw new Error("cast is not signed by its publicKey");
  if (body.visibility && body.visibility !== "public") throw new Error("only public casts belong here");
  const kind = body.kind === "card" ? "card" : "need";
  const handle = String(body.handle || "").toLowerCase();
  if (!handle.includes("@")) throw new Error("cast needs a handle");
  const id = kind === "need" ? await stableId("need", handle, body.needId || body.needText || "") : await stableId("card", handle);
  const record = {
    id, kind, handle, publicKey: body.publicKey, cardUrl: body.cardUrl || null, rpc: body.rpc || null,
    needId: body.needId || null, needText: String(body.needText || "").slice(0, 300), needTags: (body.needTags || []).map(normalizeTag).filter(Boolean),
    have: (body.have || []).map(normalizeTag).filter(Boolean), glosses: body.glosses && typeof body.glosses === "object" ? body.glosses : {},
    description: String(body.description || "").slice(0, 600), tier: "world", castAt: new Date().toISOString(),
  };
  await put(env, `cast:${kind}:${id}`, record, CAST_TTL);
  const notified = await notifySubscribers(env, origin, record);
  return json({ ok: true, id, kind, expiresInSeconds: CAST_TTL, notified, sentence: SENTENCE });
}

// A cast looks like a known card to the scorer: needs match against haves, and a need-cast is also
// searchable by its own text so two people looking for each other can meet.
function castAsCard(c) {
  return { url: c.cardUrl, handle: c.handle, rpc: c.rpc, description: c.description || c.needText || "", have: c.kind === "card" ? c.have : [], glosses: c.glosses || {}, tier: "world", need: c.needTags || [] };
}

async function search(env, url) {
  const q = String(url.searchParams.get("q") || "").trim();
  const tags = [...new Set(String(url.searchParams.get("tags") || "").split(",").map(normalizeTag).filter(Boolean))];
  if (!q && !tags.length) throw new Error("q or tags required");
  const needWords = needWordsFor(q, tags);
  const casts = await kvList(env, "cast:");
  const scored = [];
  for (const c of casts) {
    const card = castAsCard(c);
    // card-casts match on their haves; need-casts match on the words of the need itself
    const m = c.kind === "card" ? scoreCard(card, tags, needWords) : scoreNeedCast(c, tags, needWords);
    if (m.score >= 2 && m.matched.length) scored.push({ c, m, card });
  }
  scored.sort((a, b) => b.m.score - a.m.score || a.c.handle.localeCompare(b.c.handle));
  const results = scored.slice(0, MAX_RESULTS).map(({ c, m, card }) => ({
    kind: c.kind, handle: c.handle, cardUrl: c.cardUrl, rpc: c.rpc, publicKey: c.publicKey, tier: "world",
    matched: m.matched, score: m.score, why: c.kind === "card" ? whyLine(card, m, q || tags.join(" ")) : `${c.handle} is looking for the same thing: "${c.needText}".`,
    needText: c.needText || null, have: card.have, glosses: card.glosses, castAt: c.castAt,
  }));
  return json({ query: q, tags, searched: casts.length, results, sentence: SENTENCE });
}

function scoreNeedCast(c, tags, needWords) {
  const theirs = new Set([...(c.needTags || []).flatMap(words), ...words(c.needText)]);
  const matched = [];
  let score = 0;
  for (const t of tags) if ((c.needTags || []).includes(t)) { score += 3; matched.push(t); }
  let overlap = 0;
  for (const w of needWords) if (theirs.has(w)) overlap++;
  if (overlap >= 2) { score += overlap; if (!matched.length) matched.push(c.needTags[0] || "need"); }
  return { score, matched, descHits: 0 };
}

// ---------------------------------------------------------------------------
// Subscriptions: an A2A push-notification config signed by the subscribing portal. When a new cast
// matches the subscriber's haves, the relay POSTs a signed find.hit to the subscriber's door.
async function subscribe(env, body) {
  if (!body || !body.publicKey || !body.sig) throw new Error("subscription needs publicKey and sig");
  if (!(await verifyPayload(body, body.publicKey))) throw new Error("subscription is not signed by its publicKey");
  const cfg = body.config || {};
  if (!/^https:\/\//.test(String(cfg.url || ""))) throw new Error("config.url must be https");
  const handle = String(body.handle || "").toLowerCase();
  const id = await stableId("sub", handle, cfg.url);
  const record = { id, handle, publicKey: body.publicKey, url: cfg.url, token: String(cfg.token || ""), taskId: String(cfg.taskId || "*"), have: (body.have || []).map(normalizeTag).filter(Boolean), glosses: body.glosses || {}, description: String(body.description || "").slice(0, 600), createdAt: new Date().toISOString() };
  await put(env, `sub:${id}`, record, SUB_TTL);
  return json({ ok: true, id, expiresInSeconds: SUB_TTL, sentence: SENTENCE });
}

async function unsubscribe(env, body) {
  if (!body || !body.publicKey || !body.sig) throw new Error("needs publicKey and sig");
  if (!(await verifyPayload(body, body.publicKey))) throw new Error("not signed by its publicKey");
  const id = await stableId("sub", String(body.handle || "").toLowerCase(), String((body.config || {}).url || ""));
  await env.RELAY.delete(`sub:${id}`);
  return json({ ok: true, id });
}

// For a new need-cast, find subscribers whose haves fit it and deliver a find.hit to each.
async function notifySubscribers(env, origin, castRecord) {
  if (castRecord.kind !== "need") return 0;
  const subs = await kvList(env, "sub:");
  const needWords = needWordsFor(castRecord.needText, castRecord.needTags);
  let delivered = 0;
  for (const s of subs) {
    if (s.handle === castRecord.handle) continue;
    const asCard = { url: s.url, handle: s.handle, rpc: s.url, description: s.description, have: s.have, glosses: s.glosses, tier: "world" };
    const m = scoreCard(asCard, castRecord.needTags, needWords);
    if (m.score < 2 || !m.matched.length) continue;
    const hit = await relaySign(env, {
      v: 1, type: "find.hit", via: "relay", relay: origin, needId: castRecord.needId, needText: castRecord.needText, needTags: castRecord.needTags,
      from: { handle: castRecord.handle, cardUrl: castRecord.cardUrl, rpc: castRecord.rpc, publicKey: castRecord.publicKey },
      matchedTags: m.matched, why: `${castRecord.handle} is looking for ${castRecord.needText}; you have ${m.matched.join(", ")}.`, at: new Date().toISOString(),
    });
    try {
      const res = await fetch(s.url, {
        method: "POST", headers: { "content-type": "application/json", "A2A-Version": "1.0", ...(s.token ? { authorization: `Bearer ${s.token}` } : {}) },
        body: JSON.stringify({ jsonrpc: "2.0", id: hit.needId || crypto.randomUUID(), method: "SendMessage", params: { message: {
          messageId: await stableId("hit", s.id, castRecord.id), contextId: "", taskId: s.taskId, role: "ROLE_AGENT", parts: [{ text: hit.why }],
          metadata: { handle: `relay@${new URL(origin).host}`, cardUrl: `${origin}/.well-known/relay.json`, action: hit }, extensions: [HAAH_URI], referenceTaskIds: [] } } }),
      });
      if (res.ok) delivered++;
    } catch {}
  }
  return delivered;
}

// ---------------------------------------------------------------------------
function json(obj, status = 200) {
  return new Response(JSON.stringify(obj, null, 2), { status, headers: { "content-type": "application/json", "access-control-allow-origin": "*" } });
}
function text(s, status = 200) {
  return new Response(s, { status, headers: { "content-type": "text/plain; charset=utf-8" } });
}

// ---- SHARED MATCH BEGIN (pure functions; lifted verbatim into the relay at build; a test asserts equality) ----
// Function words never count as a match. Two of these in common is not a fit.
const STOPWORDS = new Set(("a an the and or of in on at to for with by from is are be me my i you your who that this it as we our find need want looking someone somebody person people help " +
  "has have had having was were been being will would could should can may might must shall do does did done doing " +
  "not no nor own real more most some any all each every both few than then there here when where which what how why also just only very " +
  "into onto over under about after before again ever never now new old one two three get got give gave like make made take took come came go went " +
  "its his her their them they she he him hers ours yours out off per via yes too able much many such same other another whether while still").split(/\s+/));

function normalizeTag(t) {
  return String(t || "")
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function words(text) {
  return String(text || "").toLowerCase().replace(/[^a-z0-9\s-]/g, " ").split(/[\s-]+/).filter((w) => w.length > 2 && !STOPWORDS.has(w));
}

// Deterministic match of need tags against one known card's haves.
function scoreCard(card, needTags, needWords) {
  const matched = [];
  let score = 0;
  const haveGloss = (t) => (card.glosses && card.glosses[t]) || "";
  for (const h of card.have) {
    const hw = new Set([...words(h), ...words(haveGloss(h))]);
    if (needTags.includes(h)) {
      score += 3;
      matched.push(h);
      continue;
    }
    let overlap = 0;
    for (const t of needTags) for (const w of words(t)) if (hw.has(w)) overlap++;
    if (overlap) {
      score += 2 * overlap;
      matched.push(h);
      continue;
    }
    let gl = 0;
    for (const w of needWords) if (hw.has(w)) gl++;
    if (gl) {
      score += gl;
      matched.push(h);
    }
  }
  const dw = new Set(words(card.description));
  let desc = 0;
  for (const w of needWords) if (dw.has(w)) desc++;
  score += desc;
  return { score, matched, descHits: desc };
}

function whyLine(card, m, needText) {
  const tag = m.matched[0];
  const gloss = tag && card.glosses && card.glosses[tag] ? ` ("${card.glosses[tag]}")` : "";
  if (tag) return `You need ${needText}; ${card.handle} has ${tag}${gloss}.`;
  return `You need ${needText}; ${card.handle}'s card mentions it (${m.descHits} matching words in their description).`;
}

// Score one card against a thread's need. Shared by find and by add_known_card,
// so an open thread keeps collecting candidates as new cards arrive.
function candidateFor(card, needTags, needWords, needText) {
  const m = scoreCard(card, needTags, needWords);
  if (m.score < 2 || !m.matched.length) return null;
  return { cardUrl: card.url, handle: card.handle, rpc: card.rpc, tier: card.tier, score: m.score, matchedTags: m.matched, why: whyLine(card, m, needText), addedAt: new Date().toISOString() };
}

function needWordsFor(needText, needTags) {
  return [...new Set([...words(needText), ...needTags.flatMap(words)])];
}
// ---- SHARED MATCH END ----

// ---- SHARED SIGNING BEGIN (pure helpers; lifted verbatim into the relay at build) ----
const b64u = (buf) => btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
const unb64u = (s) => Uint8Array.from(atob(String(s).replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - (s.length % 4)) % 4)), (c) => c.charCodeAt(0));

// Canonical JSON: sorted keys, no whitespace, so both sides sign the same bytes.
function canonical(v) {
  if (v === null || typeof v !== "object") return JSON.stringify(v);
  if (Array.isArray(v)) return "[" + v.map(canonical).join(",") + "]";
  return "{" + Object.keys(v).sort().map((k) => JSON.stringify(k) + ":" + canonical(v[k])).join(",") + "}";
}

async function keyId(publicKeyB64u) {
  const h = await crypto.subtle.digest("SHA-256", unb64u(publicKeyB64u));
  return b64u(h).slice(0, 16);
}

// Verify a signed object against a base64url raw Ed25519 public key. The sig and kid fields are
// excluded from the signed bytes.
async function verifyPayload(signed, pubB64u) {
  try {
    const { sig, kid, ...payload } = signed;
    const key = await crypto.subtle.importKey("raw", unb64u(pubB64u), { name: "Ed25519" }, false, ["verify"]);
    return await crypto.subtle.verify({ name: "Ed25519" }, key, unb64u(sig), new TextEncoder().encode(canonical(payload)));
  } catch {
    return false;
  }
}
// ---- SHARED SIGNING END ----
