#!/usr/bin/env node
// Assemble relay/src/index.js from relay.template.js + two blocks lifted verbatim from portal/src/index.js.
// One source for the scorer and the signing helpers; the test suite asserts the lifted text matches.
import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const here = dirname(fileURLToPath(import.meta.url));
const portal = readFileSync(join(here, '../portal/src/index.js'), 'utf8');
const tpl = readFileSync(join(here, 'src/relay.template.js'), 'utf8');
const lift = (begin, end) => { const a = portal.indexOf(begin), b = portal.indexOf(end, a); if (a < 0 || b < 0) throw new Error('marker missing: ' + begin); return portal.slice(a, portal.indexOf('\n', b) + 1); };
const match = lift('// ---- SHARED MATCH BEGIN', '// ---- SHARED MATCH END');
const signing = lift('// ---- SHARED SIGNING BEGIN', '// ---- SHARED SIGNING END');
const out = '// GENERATED by relay/build.mjs from relay.template.js + blocks lifted from portal/src/index.js. Do not edit by hand.\n' + tpl.replace('// @@SHARED-MATCH@@\n', match).replace('// @@SHARED-SIGNING@@\n', signing);
writeFileSync(join(here, 'src/index.js'), out);
execSync('node --check ' + join(here, 'src/index.js'));
console.log(`relay/src/index.js assembled: ${out.split('\n').length} lines (match ${match.split('\n').length}, signing ${signing.split('\n').length})`);
